### PR TITLE
Added scrambler

### PR DESCRIPTION
**Pull request by batesandy123**
I added the ability to scramble a Rubik cube. This will automatically reset the target color for the solver class.

### CODE REVIEW

**Comment by lymacasm** [comment]
@bates-andy123  Did this work on your machine? Nothing happens when I press any of the buttons on mine.

**Comment by lymacasm** [comment]
This is what I get when I click a button
screen shot 2015-04-12 at 10 00 46 am

**Comment by batesandy123** [comment]
I took the jQuery library out. When I made that branch. I think next time I will leave it in for simplicity. You have to place the jQuery library in the app/static folder.

@lymacasm

**Comment by lymacasm** [comment]
Awesome, it works. I think we should keep the library in, that way we don't need to copy it in every time we checkout master. I'll merge the pull request, and then merge the jquery addition into master.

**Pull request merged**
